"""Начальная схема: пользователи, тикеты, контент, рассылки, аккаунты.

initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 22:34:53.778512
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_admins'))
    )
    op.create_table('banned_users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('banned_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_banned_users'))
    )
    op.create_table('bot_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_bot_settings'))
    )
    op.create_table('broadcast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_results'))
    )
    with op.batch_alter_table('broadcast_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_results_broadcast_id'), ['broadcast_id'], unique=False)

    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=24), nullable=False),
    sa.Column('buttons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('blocked', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_table('connected_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('phone_masked', sa.String(length=32), nullable=True),
    sa.Column('session_encrypted', sa.Text(), nullable=False),
    sa.Column('notify_target', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_accounts'))
    )
    op.create_table('menu_buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('icon_emoji_id', sa.String(length=32), nullable=True),
    sa.Column('style', sa.String(length=16), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('row_width', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_buttons'))
    )
    op.create_table('portfolio_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('icon_emoji_id', sa.String(length=32), nullable=True),
    sa.Column('style', sa.String(length=16), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_links'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bot_username', sa.String(length=64), nullable=True),
    sa.Column('users_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('extra_links', sa.JSON(), nullable=False),
    sa.Column('image_file_id', sa.String(length=256), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('quick_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=24), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quick_replies'))
    )
    op.create_table('ticket_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_categories'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_blocked_bot', sa.Boolean(), nullable=False),
    sa.Column('active_ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_title', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], name=op.f('fk_tickets_category_id_ticket_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sqlite_autoincrement=True,
    )
    # Номера тикетов начинаются с 1001 и на SQLite (на PostgreSQL — через Identity).
    if op.get_bind().dialect.name == "sqlite":
        op.execute("INSERT INTO sqlite_sequence (name, seq) VALUES ('tickets', 1000)")
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.create_index('ix_tickets_user_status', ['user_id', 'status'], unique=False)

    op.create_table('ticket_message_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_message_links_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_message_links')),
    sa.UniqueConstraint('chat_id', 'message_id', name='uq_ticket_link_chat_msg')
    )
    with op.batch_alter_table('ticket_message_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_message_links_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=8), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_messages_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_messages_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_messages_ticket_id'))

    op.drop_table('ticket_messages')
    with op.batch_alter_table('ticket_message_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_message_links_ticket_id'))

    op.drop_table('ticket_message_links')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_tickets_user_status')
        batch_op.drop_index(batch_op.f('ix_tickets_status'))

    op.drop_table('tickets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_seen_at'))

    op.drop_table('users')
    op.drop_table('ticket_categories')
    op.drop_table('quick_replies')
    op.drop_table('projects')
    op.drop_table('portfolio_links')
    op.drop_table('menu_buttons')
    op.drop_table('connected_accounts')
    op.drop_table('broadcasts')
    with op.batch_alter_table('broadcast_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_results_broadcast_id'))

    op.drop_table('broadcast_results')
    op.drop_table('bot_settings')
    op.drop_table('banned_users')
    op.drop_table('admins')
    # ### end Alembic commands ###
